# Generated by Django 5.1.1 on 2024-09-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.IntegerField()),
                ('password', models.CharField(max_length=40)),
                ('confirm_password', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=700)),
                ('Profile_image', models.ImageField(upload_to='image')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('last_login', models.TimeField()),
            ],
        ),
    ]
