# Generated by Django 5.1.1 on 2024-09-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='Profile_image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='last_login',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
